Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,7 +12,7 @@ inputs:
   encryption_password:
     description: 'Encryption key (min 32 characters)'
     required: true
-  action-type:
+  action_type:
     description: 'Select operation type (backup or restore)'
     required: false
     default: 'backup'
@@ -32,12 +32,16 @@ inputs:
 runs:
   using: 'composite'
   steps:
-
+        
     - name: Validate action type
       shell: bash
       run: |
-        if [[ "${{ inputs.action-type }}" != "backup" && "${{ inputs.action-type }}" != "restore" ]]; then
-          echo "::error ::Invalid action-type. Must be 'backup' or 'restore'"
+        if [[ "${{ inputs.action_type }}" != "backup" && "${{ inputs.action_type }}" != "restore" ]]; then
+          echo "::error ::Invalid action_type. Must be 'backup' or 'restore'"
+          exit 1
+        fi
+        if [[ "${{ inputs.otp_request_type }}" != "MAIL" && "${{ inputs.action-type }}" != "AUTHENTICATOR" ]]; then
+          echo "::error ::Invalid otp_request_type. Must be 'MAIL' or 'AUTHENTICATOR'"
           exit 1
         fi
 
@@ -46,15 +50,15 @@ runs:
       run: chmod -R +x ${{ github.action_path }}/scripts
 
     - name: Run Shield Backup
-      if: ${{ inputs.action-type == 'backup' }}
-      uses: ${{ github.action_path }}/shield
+      if: ${{ inputs.action_type == 'backup' }}
+      uses: ./shield
       with:
         activation_code: ${{ inputs.activation_code }}
         encryption_password: ${{ inputs.encryption_password }}
         
     - name: Run Restore
-      if: ${{ inputs.action-type == 'restore' }}
-      uses: ${{ github.action_path }}/restore
+      if: ${{ inputs.action_type == 'restore' }}
+      uses: ./restore
       with:
         activation_code: ${{ inputs.activation_code }}
         encryption_password: ${{ inputs.encryption_password }}
